version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: freshfarm_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: freshfarm
      MONGO_INITDB_ROOT_USERNAME: emmanuel
      MONGO_INITDB_ROOT_PASSWORD: Emma55527378.
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: freshfarm_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: freshfarm_app
    container_name: freshfarm_app
    restart: always
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://emmanuel:Emma55527378.@freshfarm_mongo:27017/admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/freshfarm
      - /freshfarm/node_modules
    command: ["npm", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
