name: Run Tests Before Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Docker Compose Up
      run: docker-compose up --build -d
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        NODE_ENV: ${{ secrets.NODE_ENV }}

    - name: Wait for services to be ready
      run: |
        echo "Waiting for containers to be ready..."
        sleep 30  # Wait for the services to fully start

    - name: List running containers
      run: docker ps -a

    # - name: Show logs for debugging (freshfarm_app container)
    #   run: docker-compose logs freshfarm_app

    - name: Check if freshfarm_app is healthy
      run: |
        container_health=$(docker inspect --format '{{.State.Health.Status}}' freshfarm_app)
        if [[ "$container_health" != "healthy" ]]; then
          echo "Container freshfarm_app is not healthy. Exiting."
          exit 1
        fi

    - name: Run tests
      run: |
        echo "Running tests..."
        docker-compose exec -T app npm test --detectOpenHandles test/auth.test.js

    - name: Tear down
      if: always()
      run: docker-compose down
