name: Run Tests Before Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: ndeloof/setup-docker-compose@v1

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.test.yml up --build -d

    - name: Wait for services
      run: sleep 10

    - name: Run tests
      run: docker-compose -f docker-compose.test.yml exec -T <test-service> npm test

    - name: Tear down
      run: docker-compose -f docker-compose.test.yml down
