name: Run Tests Before Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: ndeloof/setup-docker-compose@v1

    - name: Docker Compose Up
      run: docker-compose up --build -d

    - name: Wait for services to be ready
      run: sleep 10

    - name: List running containers
      run: docker ps -a

    - name: Show logs for debugging
      run: docker-compose logs

    - name: Run tests
      run: docker-compose exec -T app npm test

    - name: Tear down
      if: always()
      run: docker-compose down
